export const MESSAGE_ADDED_REQUEST='MESSAGE_ADDED_REQUEST'
export const MESSAGE_ADDED_SUCCESS='MESSAGE_ADDED_SUCCESS'
export const MESSAGE_ADDED_FAIL='MESSAGE_ADDED_FAIL'

export const MESSAGE_UPDATE_REQUEST='MESSAGE_UPDATE_REQUEST'
export const MESSAGE_UPDATE_SUCCESS='MESSAGE_UPDATE_SUCCESS'
export const MESSAGE_UPDATE_FAIL='MESSAGE_UPDATE_FAIL'